# Generated by Django 2.1.1 on 2018-09-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DLUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.IntegerField()),
                ('range_end', models.IntegerField()),
                ('status', models.CharField(max_length=127)),
                ('left', models.IntegerField()),
                ('alloted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DLUser')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1023)),
                ('headers', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DLUser')),
            ],
        ),
        migrations.CreateModel(
            name='PoolUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=127)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DLUser')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pool'),
        ),
    ]
